package com.example.gallerywithmusic

public class Music(private var title: String, private var singer:String, private var id: String)

object VideoSerial {
    private var angry = arrayOf<Music>(
        Music("IDGAF", "Dua Lipa", "Mgfe5tIwOj0"),
        Music("I Hate Everything About You", "Three Days Grace", "d8ekz_CSBVg"),
        Music("Love the Way You Lie", "Eminem", "uelHwf8o7_U"),
        Music("Everything About You", "Ugly Kid Joe", "byEGjLU2egA"),
        Music("Bad Guy", "Billie Eilish", "DyDfgMOUjCI"),
        Music("Killing in the Name", "Rage Against the Machine", "bWXazVhlyxQ"),
        Music("One Step Closer", "Linkin Park", "4qlCC1GOwFw"),
        Music("You Don't Own Me", "SAYGRACE (ft. G-Eazy)", "DosIvd-FdhI"),
        Music("Before He Cheats", "Carrie Underwood", "WaSy8yy-mr8"),
        Music("Rolling in the Deep", "Adele", "rYEDA3JcQqw"),
        Music("Chop Suey!", "System of a Down", "CSvFpBOe8eY"),
        Music("Bury a Friend", "Billie Eilish", "HUHC9tYz8ik"),
        Music("This is America", "Childish Gambino", "VYOjWnS4cMY"),
        Music("Irreplaceable", "Beyonce", "2EwViQxSJJQ"),
        Music("Caught Out There", "Kelis", "N3JFwd1bk4Q"),
        Music("Fighter", "Christina Aguilera", "PstrAfoMKlc"),
        Music("Kim", "Eminem", "-SeVN2u5Axc"),
        Music("Picture to Burn", "Taylor Swift", "yCMqcFAigRg"),
        Music("Somebody That I Used to Know", "Gotye featuring Kimbra", "8UVNT4wvIGY"),
        Music("Mama's Broken Heart", "Miranda Lambert", "7yg05svXp98"),
        Music("Praying", "Kesha", "v-Dur3uXXCQ"),
        Music("So What", "Pink", "FJfFZqTlWrQ"),
        Music("Don't", "Ed Sheeran", "3TqGEbROFd4"),
        Music("Sorry Not Sorry", "Demi Lovato", "-MsvER1dpjM"),
        Music("Down With the Sickness", "Disturbed", "09LTT0xwdfw"),
        Music("Black Skinhead", "Kanye West", "q604eed4ad0"),
        Music("Look What You Made Me Do", "Taylor Swift", "3tmd-ClpJxA"),
        Music("Hit 'em up Style", "Blu Cantrell", "LMOKlXfXn50"),
        Music("Don't Look Back in Anger", "Oasis", "r8OipmKFDeM"),
        Music("Bitch", "Meredith Brooks", "_ivt_N2Zcts"),
        Music("In the End", "Linkin Park", "eVTXPUF4Oz4"),
        Music("Best Thing I Never Had", "Beyonce", "FHp2KgyQUFk"),
        Music("Masters of War", "Bob Dylan", "JEmI_FT4YHU"),
        Music("Hate Me", "Ellie Goulding, Juice Wrld", "UZwi9SHgzGY"),
        Music("Bust Your Windows", "Jazmine Sullivan", "mOzdfaEPaR0"),
        Music("Without Me", "Halsey", "ZAfAud_M_mg"),
        Music("Ring the Alarm", "Beyonce", "eY_mrU8MPfI")
    )

    private var disgust = arrayOf<Music>(
        Music("Hate Myself", "NF", "1f6F7tGDcQw"),
        Music("Disgustipated", "Tool", "CmJYZ1NIn1Y"),
        Music("The Dope Show", "Marilyn Manson", "5R682M3ZEyk"),
        Music("Liar", "Rollins Band", "iaysTVcounI"),
        Music("Fumbling Towards Ecstasy", "Sarah McLachlan", "vf727y_HsOE"),
        Music("Sick of You", "Gwar", "Dbnm-0r3suM"),
        Music("Icky Thump", "The White Stripes", "1OjTspCqvk8"),
        Music("Rats", "Ghost B.C.", "C_ijc7A5oAc"),
        Music("Reptile", "The Church", "x6Mx5xKOMAk"),
        Music("Sick, Sick, Sick", "Queens of the Stone Age", "oHDaKtx6bGY"),
        Music("Sick and Tired", "Anastacia", "HzfyCuPVpCY"),
        Music("Walking Contradiction", "Green Day", "UymN5scMpZM"),
        Music("Sick of Being Lonely", "Field Mob", "0BVwgRTISOQ"),
        Music("My Own Summer (Shove it)", "Deftones", "XOzs1FehYOA"),
        Music("Bored To Death", "blink-182", "lic0oCDMfwk"),
    )

    private var fear = arrayOf<Music>(
        Music("Somebody's Watching Me", "Rockwell", "7YvAYIJSSZY"),
        Music("The Fear", "Lily Allen", "q-wGMlSuX_c"),
        Music("Fear", "Sade", "0iD9Hh8yOu8"),
        Music("Fear of the Dark", "Iron Maiden", "bePCRKGUwAY"),
        Music("Fear of Sleep", "The Strokes", "xMpVCjW8F8M"),
        Music("Fear of Dying", "Poppy", "5PQoSzZkYVI"),
        Music("Welcome to My Nightmare", "Alice Cooper", "VDTwL15ZHZs"),
        Music("Fearless", "Taylor Swift", "7lLigiVgJsE"),
        Music("FEAR", "Kendrick Lamar", "jdbQYDkNjfk"),
        Music("Fear", "SEVENTEEN", "ap14O5-G7UA"),
        Music("The Fear", "The Score", "K5U7b_E14cE"),
        Music("Pretty Little Fears", "6Lack", "iSgUMPHQEWw"),
        Music("Fear The Future", "St.Vincent", "-v7rkdDldF4"),
        Music("Crawling", "Linkin Park", "Gd9OhYroLN0"),
        Music("The Reaper", "Blue Oyster Cult", "Dy4HA3vUv2c"),
        Music("Never Scared", "Bone Crusher", "ryIjCkw3Jfg"),
        Music("I Will Fear No More", "The Afters", "wMmmbJlWhtk"),
        Music("Help!", "The Beatles", "2Q_ZzBGPdqE"),
        Music("Paranoid", "Black Sabbath", "0qanF-91aJo"),
        Music("Fear is the Weakness", "In Flames", "HuYnfcgiERg"),
        Music("Only Fear of Death", "2Pac", "srnjSlHR8Vs"),
        Music("What, Me Worry?", "Portugal. The Man", "FUBRjHDnzE8"),
        Music("There Goes The Fear", "Doves", "SneuvKIkM3A"),
        Music("Runnin'", "Blood Orange", "fA2Ese62YTU"),
        Music("Scared of Beautiful", "Brandy", "4xfN6Dk6aAo"),
        Music("Fear for Nobody", "Maneskin", "Ln-zDvQT3sQ"),
        Music("Mr. Fear", "Siames", "EKLWC93nvAU"),
        Music("scared", "Jeremy Zucker", "dWXH6RfeQ0U"),
        Music("Fear & Loathing", "Marina And The Diamonds", "9txg0XicoJ0"),
        Music("Paranoia", "Chance The Rapper", "0vqNzbdgvq4"),
        Music("Fear of a Blank Planet", "Porcupine Tree", "G9Dyy1oNkyk"),
        Music("Doubt", "Twenty One Pilots", "MEiVnNNpJLA"),
        Music("Fear Inoculum", "Tool", "q7DfQMPmJRI"),
        Music("No More Teardrops", "Vic Mensa", "zAG8V5cQ25g"),
        Music("Creature Fear", "Bon Iver", "P_2SOYI8AfQ"),
        Music("Save Myself", "Ed Sheeran", "qXM0JdAwabU"),
        Music("Scared To Live", "The Weeknd", "MzsU_sn2aIE"),
        Music("Terrified", "Childish Gambino", "ZIEgfEIdEag"),
        Music("Fear", "X Ambassadors", "0y4ynYUuQl0"),
        Music("Fearmonger", "Saba", "GgKKHRMZNsg")
    )

    private var happy = arrayOf<Music>(
        Music("Sunroof", "Nicky Youre", "G5xSLbYMr-I"),
        Music("I Got You", "James Brown, The Famous Flames", "pTdihu-mp90"),
        Music("Don't Stop Me Now", "Queen", "HgzGwKwLmgM"),
        Music("Walking on Sunshine", "Katrina, The Waves", "iPUmE-tne5U"),
        Music("Lovely Day", "Bill Withers", "bEeaS6fuUoA"),
        Music("Tightrope", "Janelle Monae", "pwnefUaKCbc"),
        Music("Three Little Birds", "Bob Marley, The Wailers", "HNBCVM4KbUM"),
        Music("Shout", "Isley Brothers", "rWRsJ-mDU5o"),
        Music("Dancing Queen", "ABBA", "xFrGuyw1V8s"),
        Music("A Beautiful Morning", "The Rascals", "ykLVZR7RG_w"),
        Music("You Make My Dreams", "Hall, Oates", "EErSKhC0CZs"),
        Music("I Wanna Dance with Somebody", "Whitney Houston", "ynkaGd_zGwE"),
        Music("Good Vibrations", "The Beach Boys", "apBWI6xrbLY"),
        Music("Feel Right", "Mark Ronson (ft.Mystikal)", "ognnZ3r2qyQ"),
        Music("Sir Duke", "Wonder", "6sIjSNTS7Fs"),
        Music("I Can See Clearly Now", "Johnny Nash", "b0cAWgTPiwM"),
        Music("Dance to the Music", "Sly, The Family Stone", "Jn2PNlhvy8E"),
        Music("All You Need Is Love", "The Beatles", "qS3NYABbfZc"),
        Music("September", "Earth, Wind & Fire", "xqVDjkXSyYI"),
        Music("Blister in the Sun", "The Violent Femmes", "G89chAA4l8s"),
        Music("Happy", "Pharrell Williams", "ZbZSe6N_BXs"),
        Music("The Way You Make Me Feel", "Michael Jackson", "HzZ_urpj4As"),
        Music("Kites Are Fun", "Free Design", "epZOKYrVAn0"),
        Music("Can't Stop the Feeling", "Justin Timberlake", "ru0K8uYEZWw"),
        Music("I'm Coming Out", "Diana Ross", "vqUVFukbrbU"),
        Music("Roam", "The B-52s", "e_ZOW0fVNxQ"),
        Music("Don't Worry, Be Happy", "Bobby McFerrin", "68vZX2uUKKA"),
        Music("Groove Is in the Heart", "Deee-Lite", "etviGf1uWlg"),
        Music("I Really Like You", "Carly Rae Jepsen", "qV5lzRHrGeg"),
        Music("It's Oh So Quiet", "Bjork", "hG7QFTalIns"),
        Music("Love On Top", "Beyonce", "HzC9X_O7bJQ"),
        Music("Shiny Happy People", "REM", "HEeucik5Zr4"),
        Music("Here Comes the Sun", "The Beatles", "GKdl-GCsNJ0"),
        Music("Paper Rings", "Taylor Swift", "8zdg-pDF10g"),
        Music("Call Me Maybe", "Carly Rae Jepsen", "fWNaR-rxAic"),
        Music("Signed, Sealed, Delivered", "Stevie Wonder", "6To0fvX_wFA"),
        Music("Keep Driving", "Harry Styles", "qbcmsEIHWeE"),
        Music("Accidentally in Love", "Counting Crows", "xgyT0z7-5ts"),
        Music("Dog Days Are Over", "Florence and the Machine", "iWOyfLBYtuU"),
        Music("Classic", "MKTO", "1vhxu2zdPOM")
    )

    private var neutral = arrayOf<Music>(
        Music("Diamonds on the Soles of Her Shoes", "Paul Simon", "-I_T3XvzPaM"),
        Music("Why", "Tracy Chapman", "ntn0OJWH8yQ"),
        Music("Red Shoes", "Elvis Costello", "pS8oaMFsBEk"),
        Music("Message in a Bottle", "The Police", "MbXWrmQW-OE"),
        Music("Typical World", "Will, The Bushmen", "5nkvpvt-JQM"),
        Music("Midnight Train to Georgia", "Gladys Knight, The Pips", "A0F9lh8TiSM"),
        Music("Blackbird", "The Beatles", "bVXQKNu8mdw"),
        Music("Overdue", "Jillian Jacqueline", "UP1F1-zZZes"),
        Music("Green Mountain State", "Trevor Hall", "vNKJJ2nkTKw"),
        Music("Suzanne", "Leonard Cohen", "svitEEpI07E"),
        Music("Homeward Bound", "Simon, Garfunkel", "JKCVAXhVMkY"),
        Music("Sunshine on My Shoulders", "John Denver", "diwuu_r6GJE"),
        Music("Instant Karma", "John Lennon", "7-SSa-D1i-M"),
        Music("Everywhere", "Fleetwood Mac", "YF1R0hc5Q2I"),
        Music("Amie", "Pure Prairie League", "KLuCKpGhGDs"),
        Music("Somewhere Only We Know", "Keane", "Oextk-If8HQ"),
        Music("When The Stars Go Blue", "Tim McGraw", "fIZ-2FB5a3g"),
        Music("You Are Your Mother's Child", "Conor Oberst", "itHc5ngt4CA"),
        Music("The General", "Dispatch", "GdAlCXNPlCk"),
        Music("Something in the Way She Moves", "James Taylor", "f0rO8H8Jq6U")
    )

    private var sad = arrayOf<Music>(
        Music("Nothing Compares 2 U" ,"Sinead O'Connor", "0-EF60neguk"),
        Music("Only Love Can Break Your Heart" ,"Neil Young", "364qY0Oz-xs"),
        Music("Strange" ,"Celeste", "A1AJEv50Ld4"),
        Music("Teardrop" ,"Massive Attack", "u7K72X4eo_s"),
        Music("Drivers License" ,"Olivia Rodrigo", "ZmDBbnmKpqQ"),
        Music("Hurt" ,"Johnny Cash", "8AHCfZTRGiI"),
        Music("No Distance Left to Run" ,"Blur", "dgA_DlR8WsM"),
        Music("The Boxer" ,"Simon & Garfunkel", "l3LFML_pxlY"),
        Music("Someone Like You" ,"Adele", "hLQl3WQQoQ0"),
        Music("No Name #5" ,"Elliott Smith", "sXd5tbNtoGs"),
        Music("Both Sides Now" ,"Joni Mitchell", "7cBf0olE9Yc"),
        Music("I Know It's Over" ,"The Smiths", "M6o1SEj02t0"),
        Music("Lazarus" ,"David Bowie", "y-JqH1M4Ya8"),
        Music("Strange Fruit" ,"Billie Holiday", "Web007rzSOI"),
        Music("Never Felt So Alone" ,"Labrinth", "pqCVMRcj_bc"),
        Music("The River" ,"Bruce Springsteen", "lc6F47Z6PI4"),
        Music("How to Disappear Completely" ,"Radiohead", "6W6HhdqA95w"),
        Music("Someone Great" ,"LCD Soundsystem", "qwoLACv_srQ"),
        Music("Disintegration" ,"The Cure", "eRQ3irjdpDw"),
        Music("Famous Blue Raincoat" ,"Leonard Cohen", "ohk3DP5fMCg"),
        Music("Re: Stacks" ,"Bon Iver", "3w68krri0bw"),
        Music("Boots of Spanish Leather" ,"Bob Dylan", "iy6wryJMwVU"),
        Music("Neither One of Us" ,"Gladys Knight and the Pips", "IK0lebBtwm4"),
        Music("Brick" ,"Ben Folds Five", "Wt5EHAqhR1c"),
        Music("Trouble" ,"Cat Stevens", "H1tRB7-aBr8"),
        Music("Isolation" ,"Joy Division", "6x-Nl3_L1pA"),
        Music("Shipbuilding" ,"Robert Wyatt", "Res3-YX4X8g"),
        Music("Enjoy the Silence" ,"Depeche Mode", "aGSKrC7dGcY"),
        Music("Past, Present and Future" ,"The Shangri-Las", "ulSZo9EAYVw"),
        Music("Death with Dignity" ,"Sufjan Stevens", "dsGODTySH0E"),
        Music("By the Time I Get to Phoenix" ,"Isaac Hayes", "9bbdJSW3pvM"),
        Music("It's So Hard to Say Goodbye to Yesterday" ,"Boyz 2 Men", "oK9gLkXe0xw"),
        Music("A Change Is Gonna Come" ,"Otis Redding", "yyhL0ioST_U"),
        Music("Be Without You" ,"Mary J Blige", "8XNaPX6MKlU"),
        Music("Crying" ,"Roy Orbison", "qLC9o_unLq4"),
        Music("My Old Man" ,"Ian Dury", "ooPVuG8ZbNE"),
        Music("Where Dreams Go to Die" ,"John Grant", "hNfckqekxY4"),
        Music("Black Eyed Dog" ,"Nick Drake", "-y4T_wYJ7YE"),
        Music("Shivers" ,"The Boys Next Door", "FDkzfnDxCJE"),
        Music("Silver" ,"Caribou", "bbzVcaLuvbI")
    )

    private var surprise = arrayOf<Music>(
        Music("No Surprises" ,"Radiohead", "u5CVsCnxyXg"),
        Music("No Surprise" ,"Daughtry", "yyl24HRGgSU"),
        Music("Surprise" ,"Chloe", "bMlJKBXU1v4"),
        Music("Surprise, Surprise" ,"The Rolling Stones", "whfzPSgUglk"),
        Music("It Took Me by Surprise" ,"Maria Mena", "BEc8FJL9kHE"),
        Music("Surprise Surprise" ,"Billy Talent", "ZGbNq_flErA"),
        Music("Baby, What a Big Surprise" ,"Chicago", "w0xcr93xx3A"),
        Music("Surprise" ,"Filter", "dpQaEXFBXFA"),
        Music("Beautiful Surprise" ,"Tamia", "ZoU877IT4O8"),
        Music("Surprise, Surprise" ,"John Lennon", "nFibxlsPais"),
        Music("Surprise Valley" ,"Widespread Panic", "1bWQDrSfzz0"),
        Music("Surprises" ,"Billy Joel", "urdqAeRjel4"),
        Music("Surprise Surprise" ,"Celine Dion", "XK1DotwaIbg"),
        Music("No Surprises" ,"Luka Bloom", "ZClLntd6EY8"),
        Music("Sister Surprise" ,"Gary Numan", "BtGajqiB_LE"),
        Music("Surprise Me" ,"SWV", "wen-Lxg73Ww"),
        Music("A Wonderful Surprise" ,"Downtown Fiction", "-yPVIsfWw2Q"),
        Music("Certain Surprise" ,"John Martyn", "3PbqiWGQqm0"),
        Music("Welcome to Paradise" ,"Green Day", "zQ-qFkCLqLc"),
    )

    private fun randomNumber(size: Int):Int{
        return (0..size).random()
    }
    public fun setMusic(emotion: String): Music{
        val item = when (emotion) {
            "angry" -> angry[randomNumber(angry.size - 1)]
            "disgust" -> disgust[randomNumber(disgust.size - 1)]
            "fear" -> fear[randomNumber(fear.size - 1)]
            "happy" -> happy[randomNumber(happy.size - 1)]
            "neutral" -> neutral[randomNumber(neutral.size - 1)]
            "sad" -> sad[randomNumber(sad.size - 1)]
            else -> surprise[randomNumber(surprise.size - 1)]
        }
        return item
    }
}